# Generated by Django 6.0.6 on 2026-06-20 12:51

import catalog.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_modelconfiguration_encrypt_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('brand', models.CharField(blank=True, default='GROZ', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CatalogDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('catalog', 'Catalog'), ('manual', 'Manual')], default='catalog', max_length=16)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=500, upload_to=catalog.models.catalog_document_upload_path)),
                ('checksum_sha256', models.CharField(max_length=64, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('extraction_schema_version', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('review', 'Needs review'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed'), ('archived', 'Archived')], default='uploaded', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('failure_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalog.catalog')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_catalog_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('catalog_id', '-version'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExtractionPage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('empty', 'Empty'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('extraction_result', models.JSONField(blank=True, default=list)),
                ('error_summary', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_pages', to='catalog.catalogdocument')),
            ],
            options={
                'ordering': ('document_id', 'page_number'),
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('upload', 'Upload'), ('rasterize', 'Rasterize'), ('extract', 'Extract'), ('assemble', 'Assemble'), ('validate', 'Validate'), ('index', 'Index'), ('reconcile', 'Reconcile'), ('complete', 'Complete')], default='upload', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('completed_units', models.PositiveIntegerField(default=0)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('error_summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='catalog.catalogdocument')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=500)),
                ('product_code', models.CharField(blank=True, max_length=160)),
                ('raw_category', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('utilities', models.JSONField(blank=True, default=list)),
                ('materials', models.JSONField(blank=True, default=dict)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('page_start', models.PositiveIntegerField(default=0)),
                ('page_end', models.PositiveIntegerField(default=0)),
                ('extraction_confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('review_status', models.CharField(choices=[('approved', 'Approved'), ('needs_review', 'Needs review'), ('rejected', 'Rejected')], default='needs_review', max_length=16)),
                ('raw_extraction', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_families', to='catalog.catalogdocument')),
                ('normalized_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_families', to='catalog.category')),
            ],
            options={
                'ordering': ('document_id', 'page_start', 'product_name'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=160)),
                ('order_number', models.CharField(blank=True, max_length=160)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('size', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=80)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('ordering_data', models.JSONField(blank=True, default=dict)),
                ('page_start', models.PositiveIntegerField(default=0)),
                ('page_end', models.PositiveIntegerField(default=0)),
                ('source_row_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.productfamily')),
            ],
            options={
                'ordering': ('family_id', 'product_code', 'order_number', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_type', models.CharField(choices=[('product_family', 'Product family'), ('product_variant', 'Product variant'), ('manual_section', 'Manual section')], max_length=24)),
                ('text', models.TextField()),
                ('page_start', models.PositiveIntegerField(default=0)),
                ('page_end', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(max_length=64)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('qdrant_point_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('index_status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('failed', 'Failed'), ('stale', 'Stale')], default='pending', max_length=12)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=80)),
                ('embedding_dimensions', models.PositiveSmallIntegerField(default=1536)),
                ('extraction_schema_version', models.PositiveSmallIntegerField(default=2)),
                ('index_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='catalog.catalogdocument')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='catalog.productfamily')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('document_id', 'page_start', 'ordinal'),
            },
        ),
        migrations.AddIndex(
            model_name='catalogdocument',
            index=models.Index(fields=['status', 'is_active'], name='catalog_doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogdocument',
            index=models.Index(fields=['source_type', 'is_active'], name='catalog_doc_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogdocument',
            constraint=models.UniqueConstraint(fields=('catalog', 'version'), name='catalog_document_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='catalogdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('catalog',), name='catalog_document_one_active_version'),
        ),
        migrations.AddIndex(
            model_name='extractionpage',
            index=models.Index(fields=['document', 'status'], name='extract_page_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractionpage',
            constraint=models.UniqueConstraint(fields=('document', 'page_number'), name='extraction_page_unique_number'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['status', 'stage'], name='ingestion_job_state_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['document', '-created_at'], name='ingestion_job_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='productfamily',
            index=models.Index(fields=['document', 'review_status'], name='product_family_review_idx'),
        ),
        migrations.AddIndex(
            model_name='productfamily',
            index=models.Index(fields=['product_code'], name='product_family_code_idx'),
        ),
        migrations.AddIndex(
            model_name='productfamily',
            index=models.Index(fields=['normalized_category'], name='product_family_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='productfamily',
            constraint=models.UniqueConstraint(fields=('document', 'source_key'), name='product_family_unique_source'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product_code'], name='product_variant_code_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['order_number'], name='product_variant_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('family', 'source_row_hash'), name='product_variant_unique_row'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'index_status'], name='document_chunk_state_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['chunk_type', 'index_status'], name='document_chunk_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'content_hash', 'ordinal'), name='document_chunk_unique_content'),
        ),
    ]
