# Generated by Django 6.0.6 on 2026-06-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seed_catalog_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='linked_product_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
