# Generated by Django 6.0.6 on 2026-06-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_manual_chunk_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogdocument',
            name='source_schema',
            field=models.CharField(default='v2', max_length=32),
        ),
    ]
