from django.urls import path
from . import views

urlpatterns = [
    path('',          views.dashboard,    name='admin_dashboard'),
    path('login/',    views.admin_login,  name='admin_login'),
    path('logout/',   views.admin_logout, name='admin_logout'),
    path('api/upload/',   views.upload_pdf,    name='upload_pdf'),
    path('api/approve-pdf/', views.approve_pdf, name='approve_pdf'),
    path('api/update-pdf-stage/', views.update_pdf_stage, name='update_pdf_stage'),
    path('api/pdfs/',     views.list_pdfs,     name='list_pdfs'),
    path('api/pdf-preview/', views.pdf_preview, name='pdf_preview'),
    path('api/pipeline/', views.run_pipeline,  name='run_pipeline'),
    path('api/pipeline-mistral/', views.run_pipeline_mistral, name='run_pipeline_mistral'),
    path('api/pipeline-mistral-split/', views.run_pipeline_mistral_split, name='run_pipeline_mistral_split'),
    path('api/chat/',     views.admin_chat,    name='admin_chat'),
    path('api/stats/',    views.catalog_stats, name='catalog_stats'),
    path('api/ping/',     views.admin_ping,    name='admin_ping'),
    path('api/chunks/',       views.list_chunks,        name='list_chunks'),
    path('api/chunks/save/',  views.save_chunk,         name='save_chunk'),
    path('api/families/',     views.list_product_families, name='list_product_families'),
    path('api/families/save/', views.save_product_family, name='save_product_family'),
    path('api/pdf-pages/',     views.pdf_page_count,     name='pdf_page_count'),
    path('api/split-pdf/',      views.split_pdf,          name='split_pdf'),
    path('api/split-pdf-custom/', views.split_pdf_custom,   name='split_pdf_custom'),
    path('api/pipeline-split/', views.run_pipeline_split, name='run_pipeline_split'),
    path('api/delete-pdf/',      views.delete_pdf,         name='delete_pdf'),
    path('api/delete-embeddings/', views.delete_embeddings_only, name='delete_embeddings_only'),
    path('api/model-config/',      views.get_model_configuration,  name='get_model_configuration'),
    path('api/model-config/save/', views.save_model_configuration, name='save_model_configuration'),
    path('api/v2/upload/', views.upload_pdf_v2, name='upload_pdf_v2'),
    path('api/v2/jobs/<uuid:job_id>/', views.ingestion_job_status_v2, name='ingestion_job_status_v2'),
    path('api/v2/jobs/<uuid:job_id>/retry/', views.retry_ingestion_job_v2, name='retry_ingestion_job_v2'),
    path('api/v2/jobs/<uuid:job_id>/cancel/', views.cancel_ingestion_job_v2, name='cancel_ingestion_job_v2'),
    path('api/v2/documents/<uuid:document_id>/archive/', views.archive_catalog_document_v2, name='archive_catalog_document_v2'),
    path('api/v2/documents/<uuid:document_id>/index-audit/', views.index_audit_v2, name='index_audit_v2'),
    path('api/v2/documents/<uuid:document_id>/index/', views.execute_index_v2, name='execute_index_v2'),
]
